function main() {
  const props = PropertiesService.getScriptProperties();
  const folderId = props.getProperty('FOLDER_ID');
  
  if (!folderId) {
    Logger.log('❌ FOLDER_ID が設定されていません');
    return;
  }

  const folder = DriveApp.getFolderById(folderId);
  const files = folder.getFiles();
  
  while (files.hasNext()) {
    const file = files.next();
    const mimeType = file.getMimeType();
    
    // JPEG/PNG以外、または処理済み(✅)はスキップ
    if ((mimeType !== MimeType.JPEG && mimeType !== MimeType.PNG) || file.getName().startsWith('✅')) {
      continue;
    }

    Logger.log(`🚀 処理開始: ${file.getName()}`);

    try {
      processImage(file, props);
      file.setName(`✅_${file.getName()}`); // 処理済みにリネーム
      Logger.log('✅ 完了');
      return; // PoC用: 1回1枚で終了
    } catch (e) {
      Logger.log(`❌ エラー: ${e.toString()}`);
    }
  }
}

function processImage(file, props) {
  const apiKey = props.getProperty('GEMINI_API_KEY');
  const githubToken = props.getProperty('GITHUB_TOKEN');
  const repo = props.getProperty('GITHUB_REPO');

  const blob = file.getBlob();
  const base64Image = Utilities.base64Encode(blob.getBytes());
  const mimeType = file.getMimeType();
  const fileName = file.getName();
  // ファイル名を安全な文字のみに変換 (例: photo.jpg)
  const safeName = fileName.replace(/[^a-zA-Z0-9._-]/g, '');

  // --- 1. 画像を GitHub (static/images/) にアップロード ---
  // Hugo では static フォルダの中身がルートに公開されます
  const imagePath = `static/images/${safeName}`;
  uploadToGithub(repo, imagePath, base64Image, `📸 Add image: ${fileName}`, githubToken);
  Logger.log(`📤 画像アップロード完了: ${imagePath}`);

  // --- 2. Gemini で記事生成 ---
  const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
  const prompt = `
    この画像をブログ記事用に分析し、以下のJSON形式のみを出力してください。
    Markdownコードブロックは不要です。
    {
      "title": "記事タイトル(30文字以内)",
      "tags": ["タグ1", "タグ2"],
      "content": "Markdown形式の本文。施設の雰囲気や犬への対応などを記述。"
    }
  `;

  const payload = {
    contents: [{
      parts: [
        { text: prompt },
        { inline_data: { mime_type: mimeType, data: base64Image } }
      ]
    }]
  };

  const response = UrlFetchApp.fetch(apiUrl, {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  });

  if (response.getResponseCode() !== 200) {
    throw new Error(`Gemini API Error: ${response.getContentText()}`);
  }

  let rawText = JSON.parse(response.getContentText()).candidates[0].content.parts[0].text;
  rawText = rawText.replace(/```json|```/g, '').trim();
  const data = JSON.parse(rawText);

  // --- 3. Markdown 生成 (画像リンク付き) ---
  // static/images/xxx.jpg に置いた画像は、記事からは /images/xxx.jpg で参照できます
  const markdownContent = `---
title: "${data.title}"
date: ${new Date().toISOString()}
cover:
  image: "images/${safeName}"
tags: [${data.tags.map(t => `"${t}"`).join(', ')}]
aiGenerated: true
---

!${data.title}

${data.content}

---
*Generated by Gemini*
`;

  // --- 4. 記事を GitHub (content/posts/) にアップロード ---
  const postPath = `content/posts/${Date.now()}-${safeName.split('.')[0]}.md`;
  const base64Markdown = Utilities.base64Encode(markdownContent, Utilities.Charset.UTF_8);
  
  uploadToGithub(repo, postPath, base64Markdown, `🤖 AI generated: ${data.title}`, githubToken);
  Logger.log(`📤 記事アップロード完了: ${postPath}`);
}

// GitHub API アップロード用共通関数
function uploadToGithub(repo, path, contentBase64, message, token) {
  const url = `https://api.github.com/repos/${repo}/contents/${path}`;
  
  // 同名ファイルがあるかチェック（上書き用）
  let sha = null;
  try {
    const check = UrlFetchApp.fetch(url, {
      method: 'get',
      headers: { 'Authorization': `Bearer ${token}` },
      muteHttpExceptions: true
    });
    if (check.getResponseCode() === 200) {
      sha = JSON.parse(check.getContentText()).sha;
    }
  } catch (e) {}

  const payload = {
    message: message,
    content: contentBase64
  };
  if (sha) {
    payload.sha = sha;
  }

  const response = UrlFetchApp.fetch(url, {
    method: 'put',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github.v3+json'
    },
    contentType: 'application/json',
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  });

  if (response.getResponseCode() !== 201 && response.getResponseCode() !== 200) {
    throw new Error(`GitHub API Error: ${response.getContentText()}`);
  }
}
